name = "PromoBox"
client_id = "229dad93414ea254c2dd212687b831b3"
application_url = "https://promoapp.proyecto.link"
embedded = true

[webhooks]
  api_version = "2025-01"

[auth]
  redirect_urls = [
    "https://promoapp.proyecto.link/auth/callback",
    "https://promoapp.proyecto.link/auth/shopify/callback",
    "https://promoapp.proyecto.link/api/auth/callback"
  ]

[pos]
  embedded = false
