api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "promobox-discount"
type = "function"
uid = "5b241d0c-4229-bcc6-696b-03443ce71f2b8e288be2"
description = "t:description"

  [[extensions.targeting]]
  target = "purchase.product-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
